modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ftbqoptimizer"
version = "${version}"
displayName = "FTBQuestsOptimizer"
displayURL = "https://github.com/bigenergy/ftb-quests-optimizer"
authors = "Big_Energy"

[[dependencies.ftbqoptimizer]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqoptimizer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqoptimizer]]
modId = "ftbquests"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"